# Generated by Django 5.1.5 on 2025-02-02 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(help_text='Nombre completo de la empresa/organización', max_length=255)),
                ('tenant_code', models.CharField(help_text='Código corto o acrónimo para la empresa', max_length=50, unique=True)),
                ('contact_name', models.CharField(help_text='Nombre de la persona de contacto principal', max_length=255)),
                ('contact_email', models.EmailField(help_text='Correo electrónico de contacto', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono de contacto principal', max_length=50, null=True)),
                ('address_line1', models.CharField(help_text='Dirección principal (calle, número, etc.)', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Complemento de dirección (opcional)', max_length=255, null=True)),
                ('city', models.CharField(help_text='Ciudad', max_length=100)),
                ('state', models.CharField(help_text='Estado o provincia', max_length=100)),
                ('country', models.CharField(help_text='País', max_length=100)),
                ('postal_code', models.CharField(help_text='Código postal', max_length=20)),
                ('domain', models.CharField(blank=True, help_text='Dominio o subdominio personalizado', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Estado del tenant (activo=True, inactivo=False)')),
                ('subscription_plan', models.CharField(blank=True, help_text='Plan o tipo de servicio contratado', max_length=50, null=True)),
                ('subscription_status', models.BooleanField(default=True, help_text='Estado de la suscripción (activo=True, expirado=False)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha de inicio del servicio', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha de expiración del servicio', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro')),
            ],
        ),
    ]
