# Generated by Django 5.1.5 on 2025-02-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageprocessed',
            name='message',
        ),
        migrations.AddField(
            model_name='messageprocessed',
            name='message_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
