# Generated by Django 5.1.5 on 2025-02-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_messageprocessed_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocessed',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
